trigger:
  branches:
    include:
    - Feature

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build_and_Test
  jobs:
################################################################################################################################# BUILD
  - job: Build
    steps:
    - script: echo Started Build
      condition: always()

    - task: SonarCloudPrepare@1
      displayName: Preparing SonarCloud
      inputs:
        SonarCloud: 'DBnD'
        organization: '1909-sep30-net'
        scannerMode: 'MSBuild'
        projectKey: 'KSJ-DBnD'
        projectName: 'DBnD'
        extraProperties: |
          sonar.exclusions=**/lib/**
          sonar.exclusions=**/Migrations/**

    - task: AzureKeyVault@1
      continueOnError: true
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: 'Webhook'

    - task: ado-discord-webhook@1
      continueOnError: true
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Feature Pipeline Build",
              "description": "Build Pipeline started. You better hope this works...",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              }
            }]

    - task: DotNetCoreCLI@2
      displayName: Dotnet Build
      continueOnError: false
      inputs:
        command: 'build'
        workingDirectory: './DatabasesNDragons'
    - task: ado-discord-webhook@1
      continueOnError: true
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Unit Testing",
              "description": "Running xUnit tests...",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              }
            }]
    - task: DotNetCoreCLI@2
      continueOnError: false
      inputs:
        command: 'test'
        projects: '**/*Test/*.csproj'
        workingDirectory: './DatabasesNDragons'
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

    - task: ado-discord-webhook@1
      continueOnError: true
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Feature SonarCloud Analysis",
              "description": "Publishing to SonarCloud...",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              }
            }]

    - task: SonarCloudAnalyze@1
      continueOnError: false
    - task: SonarCloudPublish@1
      continueOnError: false

    - task: DotNetCoreCLI@2
      displayName: Dotnet Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        zipAfterPublish: true
        workingDirectory: './DatabasesNDragons'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        
    
    - task: PublishBuildArtifacts@1
      displayName: Publish Dotnet Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

################################################################################################################################# TEST SUCCEED
  - job: Tests_Succeeded
    dependsOn: Build
    condition: succeeded()
    steps:
    - script: echo Pipe success!

    - task: AzureKeyVault@1
      continueOnError: true
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: Webhook
    - task: ado-discord-webhook@1
      continueOnError: true
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Feature Pipeline Success!",
              "description": "The pipe passed all build and analysis processes! You can give yourself a pat on the back and feel good about yourself!",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              },
              "fields": 
              [{
                "name": "SonarCloud Metrics Link",
                "value": "https://sonarcloud.io/dashboard?id=KSJ-DBnD"
                    }]
            }]
################################################################################################################################# TEST FAILED
  - job: Tests_Failed
    dependsOn: Build
    condition: failed()
    steps:
    - script: echo Pipe failiure!
    - task: AzureKeyVault@1
      continueOnError: true
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: Webhook
    - task: ado-discord-webhook@1
      continueOnError: true
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Feature Pipeline Failed",
              "description": "Pipeline failiure due to process above",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              }
            }]
############################################################################################################################# DEPLOY
- stage: Deploy
  dependsOn:
  - Build_and_Test
  condition: succeeded()
  jobs:
  - job: Deploy_API
    steps:
    - script: echo Publishing steps started

    - task: DownloadBuildArtifacts@0
      displayName: Retrieving Build Artifacts
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.ArtifactsDirectory)'
        Contents: '**'
        TargetFolder: '$(System.DefaultWorkingDirectory)'
    - task: AzureKeyVault@1
      continueOnError: true
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: Webhook
    - task: ado-discord-webhook@1
      continueOnError: true
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Feature Pipeline API App Service Deployment",
              "description": "Attempting to deploy to app service...",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              }
            }]
########################### DEPLOY TASK

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        appType: 'webApp'
        WebAppName: 'dbndapi'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

  - job: Deployment_Success
    dependsOn: Deploy_API
    condition: succeeded()
    steps:
    - script: echo Successfully deployed!
    - task: AzureKeyVault@1
      continueOnError: true
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: Webhook
    - task: ado-discord-webhook@1
      continueOnError: true
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Deployment Success!",
              "description": "Your app has been deployed!",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              },
              "fields": 
              [{
                "name": "Hosted Link",
                "value": "https://dbndapi.azurewebsites.net/"
                    }]
            }]
  - job: Deployment_Failed
    dependsOn: Deploy_API
    condition: failed()
    steps:
    - script: echo Unsuccessfully deployed...
    - task: AzureKeyVault@1
      continueOnError: true
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: Webhook
    - task: ado-discord-webhook@1
      continueOnError: true
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Deployment Failiure",
              "description": "Your app has failed to be deployed. I blame Fred.",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              },
              "fields": 
              [{
                "name": "Hosted Link",
                "value": "https://dbndapi.azurewebsites.net/"
                    }]
            }]
############################################################################################################################# Build and Deploy Angular proj
- stage: Deploy_Angular
  dependsOn:
  - Build_and_Test
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-latest'
  variables: 
    appDir: AngularClient
  jobs:
  - job: Build_And_Deploy_Angular
    steps:
    - script: echo Beginning process
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: npm ci
      displayName: npm install
      workingDirectory: $(appDir)
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'DBnD'
        organization: '1909-sep30-net'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'DBnDAngular'
        cliProjectName: 'DBnDAngular'
        cliSources: '$(appDir)/src'
        extraProperties: |
          sonar.coverage.exclusions=**/*.spec.ts
          sonar.typescript.lcov.reportPaths=$(appDir)/coverage/$(appDir)/lcov.info

    - script: npx ng build --prod
      displayName: ng build
      workingDirectory: $(appDir)

    - script: npx ng test --browsers ChromeHeadless --no-watch --code-coverage
      continueOnError: true
      displayName: ng test
      workingDirectory: $(appDir)

    #- script: npm run lint
    #  displayName: ng lint
    #  workingDirectory: $(appDir)

    - task: SonarCloudAnalyze@1
      displayName: Run SonarCloud analysis

    - task: SonarCloudPublish@1
      displayName: Publish SonarCloud quality gate result

    - task: AzureRmWebAppDeployment@4
      displayName: Azure WebApp Deployment
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        appType: 'webApp'
        WebAppName: 'dbnd'
        packageForLinux: '$(appDir)/dist/*'
########################################################################################################################### WEB APP DEPLOYED
  - job: Deployment_Success
    dependsOn: Build_And_Deploy_Angular
    condition: succeeded()
    steps:
    - task: AzureKeyVault@1
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: 'Webhook'
    - task: ado-discord-webhook@1
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Feature Web App Successfully Deployed!",
              "description": "The DBnD Web App has been successfully deployed!",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              },
              "fields": 
              [{
                "name": "Web Application Link",
                "value": "https://dbnd.azurewebsites.net/"
                    }]
            }]
  - job: Deployment_Failiure
    dependsOn: Build_And_Deploy_Angular
    condition: failed()
    steps:
    - script: echo Pipe failiure!
    - task: AzureKeyVault@1
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: 'Webhook'
    - task: ado-discord-webhook@1
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Feature Web App Unsuccessfully Deployed...",
              "description": "Angular website deployment failed...",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              }
            }]