# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    exclude:
    - Feature/*
    - KC/*
    - Shawn/*
    - Jacob/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'DBnD'
    organization: 'dbnd-project-2'
    scannerMode: 'MSBuild'
    projectKey: 'DBnD'
    projectName: 'DBnD'

- task: SonarCloudAnalyze@1
#- task: SonarCloudPrepare@1
#  inputs:
#    SonarCloud: 'kc-SonarCloud-Connection'
#    organization: 'kc-revature-training'
#    scannerMode: 'MSBuild'
#    projectKey: 'kc-pipeline-project-test'
#    extraProperties: |
#        sonar.exclusions=**/lib/**
