# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - Feature
    exclude:
    - master/*
    - KC/*
    - Shawn/*
    - Jacob/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'DBnD'
    organization: 'dbnd-project-2'
    scannerMode: 'MSBuild'
    projectKey: 'DBnD'
    extraProperties: |
        sonar.exclusions=**/lib/**
        sonar.exclusions=**/Migrations/**

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: './DatabasesNDragons'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Test/*.csproj'
    workingDirectory: './DatabasesNDragons'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1

- task: ado-discord-webhook@1
  inputs:
    channelId: '639181531809710090'
    webhookKey: 'xNh4eYrr02Lki3xT25aFuerWFYR8vIKS4hYGcHxgrw2kDEJD6TKeWxnwYOWBBWK8klXc'
    name: 'Azure'
    messageType: 'embeds'
    embeds: 'content'