# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - Feature
    exclude:
    - master/*
    - KC/*
    - Shawn/*
    - Jacob/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'FeaturedSonar'
    organization: 'dbnd-project-2'
    scannerMode: 'MSBuild'
    projectKey: 'Featured'
    extraProperties: |
        sonar.exclusions=**/lib/**

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: './DatabasesNDragons'
    arguments: --configuration $(buildConfiguration) --collect "XPlat Code Coverage"

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: './DatabasesNDragons'

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  displayName: Publish SonarCloud quality gate result



