trigger:
  branches:
    include:
    - Jacob
    - Shawn

pool:
  vmImage: 'ubuntu-latest'
variables: 
  appDir: AngularClient

jobs:
- job: Build_And_Deploy_Angular
  steps:
  - script: echo Beginning process
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: npm install
    workingDirectory: $(appDir)
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'DBnD'
      organization: '1909-sep30-net'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'DBnDAngular'
      cliProjectName: 'DBnDAngular'
      cliSources: '$(appDir)/src'
      extraProperties: |
        sonar.coverage.exclusions=**/*.spec.ts
        sonar.typescript.lcov.reportPaths=$(appDir)/coverage/$(appDir)/lcov.info

  - script: npx ng build --prod
    displayName: ng build
    workingDirectory: $(appDir)

  - script: npx ng test --browsers ChromeHeadless --no-watch --code-coverage
    displayName: ng test
    workingDirectory: $(appDir)

  #- script: npm run lint
  #  displayName: ng lint
  #  workingDirectory: $(appDir)

  - task: SonarCloudAnalyze@1
    displayName: Run SonarCloud analysis

  - task: SonarCloudPublish@1
    displayName: Publish SonarCloud quality gate result

  - task: AzureRmWebAppDeployment@4
    displayName: Azure WebApp Deployment
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Free Trial(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
      appType: 'webApp'
      WebAppName: 'dbnd'
      packageForLinux: '$(appDir)/dist/*'
########################################################################################################################### WEB APP DEPLOYED
- job: Deployment_Success
  dependsOn: Build_And_Deploy_Angular
  condition: succeeded()
  steps:
  - task: AzureKeyVault@1
    displayName: Azure Keyvault Access for Webhook
    inputs:
      azureSubscription: 'Free Trial(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
      KeyVaultName: 'DBnD-KeyVault'
      SecretsFilter: Webhook
  - task: ado-discord-webhook@1
    displayName: Discord Webhook Message
    inputs:
      channelId: '639490810336903202'
      webhookKey: '$(Webhook)'
      name: 'Azure Devops'
      messageType: embeds
      embeds: |
          [{
            "title": "Web App Successfully Deployed!",
            "description": "The DBnD Web App has been successfully deployed!",
            "url": "https://discordapp.com",
            "color": 2247803,
            "thumbnail": 
            {
              "url": "https://static.thenounproject.com/png/266379-200.png"
            },
            "author": 
            {
              "name": "Azure Devops",
              "url": "https://dev.azure.com/kcguzman/Project-2",
              "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
            },
            "fields": 
            [{
              "name": "Web Application Link",
              "value": "https://dbnd.azurewebsites.net/"
                  }]
          }]
- job: Deployment_Failiure
  dependsOn: Build_And_Deploy_Angular
  condition: failed()
  steps:
  - script: echo Pipe failiure!
  - task: AzureKeyVault@1
    displayName: Azure Keyvault Access for Webhook
    inputs:
      azureSubscription: 'Free Trial(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
      KeyVaultName: 'DBnD-KeyVault'
      SecretsFilter: Webhook
  - task: ado-discord-webhook@1
    displayName: Discord Webhook Message
    inputs:
      channelId: '639490810336903202'
      webhookKey: '$(Webhook)'
      name: 'Azure Devops'
      messageType: embeds
      embeds: |
          [{
            "title": "Web App Unsuccessfully Deployed...",
            "description": "Deployment failed...",
            "url": "https://discordapp.com",
            "color": 2247803,
            "thumbnail": 
            {
              "url": "https://static.thenounproject.com/png/266379-200.png"
            },
            "author": 
            {
              "name": "Azure Devops",
              "url": "https://dev.azure.com/kcguzman/Project-2",
              "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
            }
          }]