# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - Feature
    exclude:
    - master/*
    - KC/*
    - Shawn/*
    - Jacob/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'DBnD'
    organization: 'dbnd-project-2'
    scannerMode: 'MSBuild'
    projectKey: 'DBnD'
    extraProperties: |
        sonar.exclusions=**/lib/**
        sonar.exlusions=**/Migrations/**

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: './DatabasesNDragons'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Test/*.csproj'
    workingDirectory: './DatabasesNDragons'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: SonarCloudAnalyze@1

- task: DotNetCoreCLI@2
  displayName: dotnet publish + zip
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true

- task: SonarCloudPublish@1
