# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - Feature
    exclude:
    - master/*
    - KC/*
    - Shawn/*
    - Jacob/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

jobs:
- job: Build
  steps:
  - script: echo Started Build
    condition: always()

  - task: ado-discord-webhook@1
    inputs:
      channelId: '639181531809710090'
      webhookKey: 'xNh4eYrr02Lki3xT25aFuerWFYR8vIKS4hYGcHxgrw2kDEJD6TKeWxnwYOWBBWK8klXc'
      name: 'Azure'
      messageType: embeds
      embeds: |
        [{
        "title": "Build Started!",
        "description" : "Your build has begun within the pipe. You best hope it don't fail, son..."
        }]
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'DBnD'
      organization: 'dbnd-project-2'
      scannerMode: 'MSBuild'
      projectKey: 'DBnD'
      extraProperties: |
          sonar.exclusions=**/lib/**
          sonar.exclusions=**/Migrations/**

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
    workingDirectory: './DatabasesNDragons'
  - task: DotNetCoreCLI@2
    continueOnError: true
    inputs:
      command: 'test'
      projects: '**/*Test/*.csproj'
      workingDirectory: './DatabasesNDragons'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
  - task: ado-discord-webhook@1
    inputs:
      channelId: '639181531809710090'
      webhookKey: 'xNh4eYrr02Lki3xT25aFuerWFYR8vIKS4hYGcHxgrw2kDEJD6TKeWxnwYOWBBWK8klXc'
      name: 'Azure'
      messageType: embeds
      embeds: |
        [{
        "title": "Build and test success!",
        "description" : "Your build succeeded and tests ran, attempting to put it into SonarCloud."
        }]

  - task: SonarCloudAnalyze@1
    continueOnError: true
  - task: SonarCloudPublish@1
    continueOnError: true

- job: PipeSucceed
  dependsOn: Build
  condition: succeeded()
  steps:
  - script: echo Pipe success!
  - task: ado-discord-webhook@1
    inputs:
      channelId: '639181531809710090'
      webhookKey: 'xNh4eYrr02Lki3xT25aFuerWFYR8vIKS4hYGcHxgrw2kDEJD6TKeWxnwYOWBBWK8klXc'
      name: 'Azure'
      messageType: embeds
      embeds: |
        [{
        "title": "Pipe Success!",
        "description" : "Your pipe succeeded and you should feel good about yourself!"
        "fields" : [{"name" : "SonarCloud", "title" : "Analysis link", "url": "https://sonarcloud.io/organizations/dbnd-project-2/projects" }]
        }]
    
- job: PipeFailed
  dependsOn: Build
  condition: failed()
  steps:
  - script: echo Pipe failiure!
  - task: ado-discord-webhook@1
    inputs:
      channelId: '639181531809710090'
      webhookKey: 'xNh4eYrr02Lki3xT25aFuerWFYR8vIKS4hYGcHxgrw2kDEJD6TKeWxnwYOWBBWK8klXc'
      name: 'Azure'
      messageType: embeds
      embeds: |
        [{
        "title": "Pipe Failed",
        "description" : "Your pipe failed and you should feel bad!"
        }]



