trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build_and_Test_Master
  jobs:
################################################################################################################################# BUILD
  - job: Build
    steps:
    - script: echo Started Build
      condition: always()

    - task: SonarCloudPrepare@1
      displayName: Preparing SonarCloud
      inputs:
        SonarCloud: 'DBnD'
        organization: '1909-sep30-net'
        scannerMode: 'MSBuild'
        projectKey: 'KSJ-DBnD'
        projectName: 'DBnD'
        extraProperties: |
          sonar.exclusions=**/lib/**
          sonar.exclusions=**/Migrations/**

    - task: AzureKeyVault@1
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Free Trial(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: Webhook
    - task: ado-discord-webhook@1
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Master Pipeline Build",
              "description": "Build Pipeline started. You better hope this works...",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              }
            }]

    - task: DotNetCoreCLI@2
      displayName: Dotnet Build
      continueOnError: false
      inputs:
        command: 'build'
        workingDirectory: './DatabasesNDragons'
    - task: ado-discord-webhook@1
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Unit Testing",
              "description": "Running xUnit tests...",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              }
            }]
    - task: DotNetCoreCLI@2
      continueOnError: false
      inputs:
        command: 'test'
        projects: '**/*Test/*.csproj'
        workingDirectory: './DatabasesNDragons'
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

    - task: ado-discord-webhook@1
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Master SonarCloud Analysis",
              "description": "Publishing to SonarCloud...",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              }
            }]

    - task: SonarCloudAnalyze@1
      continueOnError: false
    - task: SonarCloudPublish@1
      continueOnError: false

    - task: DotNetCoreCLI@2
      displayName: Dotnet Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        zipAfterPublish: true
        workingDirectory: './DatabasesNDragons'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        
    
    - task: PublishBuildArtifacts@1
      displayName: Publish Dotnet Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

################################################################################################################################# TEST SUCCEED
  - job: Tests_Succeeded
    dependsOn: Build
    condition: succeeded()
    steps:
    - script: echo Pipe success!

    - task: AzureKeyVault@1
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Free Trial(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: Webhook
    - task: ado-discord-webhook@1
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Master Pipeline Success!",
              "description": "The pipe passed all build and analysis processes! You can give yourself a pat on the back and feel good about yourself!",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              },
              "fields": 
              [{
                "name": "SonarCloud Metrics Link",
                "value": "https://sonarcloud.io/dashboard?id=KSJ-DBnD"
                    }]
            }]
################################################################################################################################# TEST FAILED
  - job: Tests_Failed
    dependsOn: Build
    condition: failed()
    steps:
    - script: echo Pipe failiure!
    - task: AzureKeyVault@1
      displayName: Azure Keyvault Access for Webhook
      inputs:
        azureSubscription: 'Free Trial(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        KeyVaultName: 'DBnD-KeyVault'
        SecretsFilter: Webhook
    - task: ado-discord-webhook@1
      displayName: Discord Webhook Message
      inputs:
        channelId: '639490810336903202'
        webhookKey: '$(Webhook)'
        name: 'Azure Devops'
        messageType: embeds
        embeds: |
            [{
              "title": "Master Pipeline Failed",
              "description": "Pipeline failiure due to process above",
              "url": "https://discordapp.com",
              "color": 2247803,
              "thumbnail": 
              {
                "url": "https://static.thenounproject.com/png/266379-200.png"
              },
              "author": 
              {
                "name": "Azure Devops",
                "url": "https://dev.azure.com/kcguzman/Project-2",
                "icon_url": "http://www.mattruma.com/wp-content/uploads/2019/04/528389819366_e7a0672f0480b3e98d21_512.png"
              }
            }]
############################################################################################################################# DEPLOY
- stage: Deploy
  dependsOn:
  - Build_and_Test
  condition: succeeded()
  jobs:
  - job: Deploy_API
    steps:
    - script: echo Publishing steps started