using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace Dbnd.Logic.Objects
{
    public class Character
    {
        private Guid characterID = Guid.NewGuid();

        public Guid CharacterID
        {
            get { return characterID; }
            set { characterID = value; }
        }
        public Guid ClientID { get; set; }

        // 3-20 alphanumeric . _ chars
        // . and _ can not be leading or trailing
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public Character(Guid clientID, string firstName, string lastName)
        {
            ClientID = clientID;
            FirstName = firstName;
            LastName = lastName;
        }

        public Character() { }

        // 'Not Null' checks for properties that are not autogenerated
        public bool RequiredFieldsNotNull()
        {
            if (String.IsNullOrEmpty(FirstName) || String.IsNullOrEmpty(LastName))
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        // Valid Name checks
        // 3-20 alphanumeric . _ chars
        // . and _ can not be leading or trailing
        public bool IsValidFirstName()
        {
            Regex regex = new Regex(@"^(?=.{3,20}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])$", RegexOptions.None, TimeSpan.FromMilliseconds(2000));
            Match match = regex.Match(FirstName);
            if (match.Success)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        public bool IsValidLastName()
        {
            Regex regex = new Regex(@"^(?=.{3,20}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])$", RegexOptions.None, TimeSpan.FromMilliseconds(2000));
            Match match = regex.Match(LastName);
            if (match.Success)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}