// <auto-generated />
using System;
using Dbnd.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Dbnd.Data.Migrations
{
    [DbContext(typeof(DbndContext))]
    [Migration("20191031021033_EntityPropertyNamesUpdate")]
    partial class EntityPropertyNamesUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Dbnd.Data.Entities.Character", b =>
                {
                    b.Property<Guid>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("character varying(75)")
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("character varying(75)")
                        .HasMaxLength(75);

                    b.HasKey("CharacterID");

                    b.HasIndex("ClientID");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("Dbnd.Data.Entities.CharacterGameXRef", b =>
                {
                    b.Property<Guid>("GameID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid");

                    b.HasKey("GameID", "ClientID");

                    b.HasIndex("ClientID");

                    b.ToTable("CharacterGameXRef");
                });

            modelBuilder.Entity("Dbnd.Data.Entities.Client", b =>
                {
                    b.Property<Guid>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying(75)")
                        .HasMaxLength(75);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("character varying(75)")
                        .HasMaxLength(75);

                    b.HasKey("ClientID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Dbnd.Data.Entities.DungeonMaster", b =>
                {
                    b.Property<Guid>("DungeonMasterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid");

                    b.HasKey("DungeonMasterID");

                    b.HasIndex("ClientID");

                    b.ToTable("DungeonMaster");
                });

            modelBuilder.Entity("Dbnd.Data.Entities.Game", b =>
                {
                    b.Property<Guid>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DungeonMasterID")
                        .HasColumnType("uuid");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("character varying(225)")
                        .HasMaxLength(225);

                    b.HasKey("GameID");

                    b.HasIndex("DungeonMasterID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Dbnd.Data.Entities.Character", b =>
                {
                    b.HasOne("Dbnd.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dbnd.Data.Entities.CharacterGameXRef", b =>
                {
                    b.HasOne("Dbnd.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dbnd.Data.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dbnd.Data.Entities.DungeonMaster", b =>
                {
                    b.HasOne("Dbnd.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dbnd.Data.Entities.Game", b =>
                {
                    b.HasOne("Dbnd.Data.Entities.DungeonMaster", "DungeonMaster")
                        .WithMany()
                        .HasForeignKey("DungeonMasterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
